"""Renders the exit-parameter calibration (data/calibration/results.json)
into the main body of docs/exit-parameter-calibration.md. Printed to
stdout for review before writing to the doc -- generated programmatically
to avoid transcription errors across a 2,304-row result set.
"""

import json
from collections import defaultdict
from pathlib import Path

CACHE_ROOT = Path(__file__).resolve().parent.parent.parent / "data" / "calibration"
ROWS = json.loads((CACHE_ROOT / "results.json").read_text())

FOLDS = ["fold_1", "fold_2", "fold_3", "fold_4"]
FOLD_LABELS = {
    "fold_1": "Train <=2022-12-31, Test 2023", "fold_2": "Train <=2023-12-31, Test 2024",
    "fold_3": "Train <=2024-12-31, Test 2025", "fold_4": "Train <=2025-08-31, Test 2025-09+",
}
BE_GRID = ["2", "2.5", "3", "4", "6", "8"]
MHD_GRID = [5, 10, 12, 15, 20, 30, 45, 60]
CURRENT_VALUES = {
    "aggressive": ("6", 10), "balanced": ("4", 15), "conservative": ("2.5", 30), "micro": ("3", 12),
}

by_key = {}
for r in ROWS:
    key = (r["asset_class"], r["fold"], r["window"], r["break_even_trigger_pct"], r["max_hold_days"], r["friction_scenario"])
    by_key[key] = r


def pct(x):
    return "n/a" if x is None else f"{x*100:.2f}%"


def num(x, digits=3):
    return "n/a" if x is None else f"{x:.{digits}f}"


out = []
w = out.append

w("# Exit-parameter calibration: break_even_trigger_pct / max_hold_days\n")
w(
    "Historical, walk-forward calibration of the two exit-intelligence parameters left as explicit "
    "judgment calls in the earlier trailing-stop/correlation calibration pass. **Read-only**: this "
    "document is evidence for a decision, not the decision itself -- no `tradepulse/` risk-profile value "
    "changes with this pass; applying any recommendation below is a separate, later, explicitly-approved "
    "step.\n"
)

w("## Methodology\n")
w(
    "- **Deterministic-layer only, not a full production backtest.** Entries are generated by the same "
    "fixed-baseline `compute_real_factors`/`weighted_composite`/`signal_from_composite` pipeline "
    "production actually runs (regime-conditioned weights were reverted ahead of this pass) -- **no "
    "AI-recommendation gate is simulated**. Historical AI opinions can't be reconstructed; this validates "
    "the deterministic layer, not \"what production would have done.\"\n"
    "- **Same-symbol re-entry matches production, verified from source**: `execution/gateway.py`/"
    "`scanner/coordinator.py` have no check blocking a BUY candidate for an already-held symbol -- only "
    "in-flight *unresolved* orders are blocked. So every BUY/STRONG_BUY signal is treated as an "
    "independent hypothetical entry, matching production's real pyramiding behavior, not a simplification. "
    "Consecutive-day signals on the same symbol are still highly correlated observations, not independent "
    "samples -- every table below reports unique-symbol/unique-date counts alongside raw trade counts.\n"
    "- **Data**: fetched via the account's own `AlpacaClient` (same IEX feed the live paper account uses). "
    "Equity universe coverage: 2020-07-27 -> 2026-09-03 (~1,500-1,536 bars/symbol, 0 gaps >5 calendar days). "
    "Crypto: 2021-01-01 -> 2026-09-04 (~2,044-2,073 bars/symbol for BTC/ETH/LTC/BCH, 0 gaps; SOL/USD has "
    "2 gaps >2 days and shorter coverage -- a genuine, isolated data-completeness issue, not generalized "
    "to the rest of the crypto universe).\n"
    "- **Gap/fill rule**: if a day's open is already at/through the operative stop, the exit fills at that "
    "open (a real gap-through is never assumed to fill at the stale stop price); otherwise, if the day's "
    "low touches the stop, the exit fills AT the stop (the standard daily-bar intraday-touch "
    "approximation).\n"
    "- **Benchmark alignment is by date, not array position** -- the relative-strength benchmark slice at "
    "day D is every benchmark bar dated <= D, an as-of lookup, never a same-length positional slice.\n"
    "- **Walk-forward folds, common calendar boundaries across every symbol** (not a per-symbol ratio "
    "split, which would train/test different symbols on different calendar eras when pooled):\n"
)
for f in FOLDS:
    w(f"  - {f}: {FOLD_LABELS[f]}")
w("")
w(
    "- **Friction, frozen before any result was examined**: equity 0/5/15 bps-per-side "
    "(gross/base/stress), crypto 0/10/30 bps-per-side (wider, reflecting real spread/venue-fee "
    "differences). Every result reported under all three -- a result that only survives Gross is labeled "
    "as such.\n"
    "- `trailing_atr_multiplier` held fixed at balanced's already-calibrated value (2.5) throughout -- "
    "this pass tests break_even_trigger_pct/max_hold_days only.\n"
)

w("## Results by fold\n")
for ac in ("equity", "crypto"):
    w(f"### {ac.capitalize()}\n")
    for fold in FOLDS:
        w(f"#### {fold} ({FOLD_LABELS[fold]})\n")

        # Full train sensitivity grid, base friction, expectancy.
        w("Train sensitivity grid (expectancy R, base friction):\n")
        header = "| BE trigger \\ max_hold_days | " + " | ".join(str(m) for m in MHD_GRID) + " |"
        w(header)
        w("|" + "---|" * (len(MHD_GRID) + 1))
        for be in BE_GRID:
            cells = []
            for mhd in MHD_GRID:
                row = by_key.get((ac, fold, "train", be, mhd, "base"))
                cells.append(num(row.get("expectancy_r")) if row and row.get("trade_count") else "n/a")
            w(f"| {be}% | " + " | ".join(cells) + " |")
        w("")

        # Best train combo by expectancy (base friction), tie-break profit factor then lower drawdown.
        candidates = []
        for be in BE_GRID:
            for mhd in MHD_GRID:
                row = by_key.get((ac, fold, "train", be, mhd, "base"))
                if row and row.get("trade_count", 0) >= 20:
                    candidates.append((row["expectancy_r"], row.get("profit_factor") or 0, -row.get("max_drawdown_r", 1e9), be, mhd))
        if not candidates:
            w("*Insufficient train sample this fold (< 20 trades in every cell) -- no combination evaluated.*\n")
            continue
        candidates.sort(reverse=True)
        best_r, best_pf, _dd, best_be, best_mhd = candidates[0]
        w(f"**Best train combination**: break_even_trigger_pct={best_be}%, max_hold_days={best_mhd} (train expectancy {num(best_r)}R, PF {num(best_pf,2)})\n")

        gross_row = by_key.get((ac, fold, "test", best_be, best_mhd, "gross")) or {}
        w(
            f"Out-of-sample TEST sample: {gross_row.get('unique_symbols', 'n/a')} unique symbols, "
            f"{gross_row.get('unique_entry_dates', 'n/a')} unique entry dates, "
            f"max {gross_row.get('max_entries_per_symbol', 'n/a')} entries in any single symbol "
            f"(avg {num(gross_row.get('avg_entries_per_symbol'), 1)} per symbol) -- see the independence "
            f"caveat in the methodology section.\n"
        )
        w("Out-of-sample TEST performance for that combination, all friction scenarios:\n")
        w("| Friction | n | Hit rate | Expectancy (R) | Profit factor | Max DD (R) |")
        w("|---|---|---|---|---|---|")
        for fric in ("gross", "base", "stress"):
            row = by_key.get((ac, fold, "test", best_be, best_mhd, fric))
            if not row:
                continue
            w(f"| {fric} | {row['trade_count']} | {pct(row.get('hit_rate'))} | {num(row.get('expectancy_r'))} | {num(row.get('profit_factor'),2)} | {num(row.get('max_drawdown_r'),1)} |")
        w("")

w("## Comparison against each profile's current values\n")
w("| Profile | Current BE trigger | Current max_hold_days | fold_4 train expectancy at that cell (base friction) |")
w("|---|---|---|---|")
for profile, (be, mhd) in CURRENT_VALUES.items():
    row = by_key.get(("equity", "fold_4", "train", be, mhd, "base"))
    w(f"| {profile} | {be}% | {mhd} | {num(row.get('expectancy_r')) if row else 'n/a'} |")
w("")

print("\n".join(out))
